### PR TITLE
got grunt set up, wrote readme

### PR DESCRIPTION
**Pull request by snollygolly**
Hey man,

I played the game a little and thought it was fun, so I was going to write a README for you.  I got a bit carried away and ended up setting you up with Grunt.  I used it for my phaser project (IsoCitySim) and really enjoyed it.  Hope you like it. :+1:

### CODE REVIEW

**Comment by ijzm** [comment]
Hi!

I'm kinda new to github and all that stuff...

What is Grunt? What does the code you are giving me do?

Thanks,

ijzm

**Comment by ijzm** [comment]
Also.. How did you found my github?

**Comment by snollygolly** [comment]
So Grunt is a javascript task runner.  It'll do a number of things, but the version I set up for you will take all your individual javascript files and uglify them to a single script.min.js.  It'll also watch all your files for changes, and re-uglify when it sees them.  Finally, it'll serve the site for you on port 9000 so you don't have to do that yourself.

I was looking for projects that were committed to recently, and yours came up. :)

**Comment by ijzm** [comment]
Oh.. okay!
I might add that later... but first i would like to have a finished product.
Thanks for the help, i'll keep that in mind :+1:

**Comment by snollygolly** [comment]
No worries.  You can feel free to not merge it if it ends up making everything more confusing.  I will tell you that if you have the time to investigate grunt and learn what it can do, it will make you development process faster and more streamlined.  Also, I'd add it in during the beginning of your project.  Trying to work it in after you're finished will make things more difficult.

Good luck either way.

**Comment by ijzm** [comment]
Okay, thanks for the tips!
I will look up those thing.

**Pull request closed without merging**
